version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nasa_air_quality
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: >
      bash -c "python manage.py migrate &&
               python manage.py ingest_sample &&
               python manage.py train_models --generate_predictions &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/nasa_air_quality
      - DEBUG=True

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data: